const redirects = [
  // Basic Redirects
  { source: "/public", destination: "/", permanent: true },
  { source: "/aboutus", destination: "/about", permanent: true },
  { source: "/certification", destination: "/certifications", permanent: true },
  { source: "/career", destination: "/careers", permanent: true },

  // AFS Redirects - MOST SPECIFIC FIRST
  { source: "/services/view/2/credit_card_processing", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/21/bpay", destination: "/solutions/consumers/bpay", permanent: true },
  { source: "/services/view/3/prepaid_card_processing", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/4/debit_card_processing_and_atm_/_pos_driving", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/4/debit_card_processing_and_atm_/", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/5/emv_and_contactless_personalization", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/services/view/15/islamic_credit_cards", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/services/view/16/_instant_card_issuance", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/technology/view/13/credit_platform", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/technology/view/13/credit_platform", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/technology/view/14/debit_platform", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/technology/view/14/debit_platform", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/17/fintech_services", destination: "/solutions/business", permanent: true },

  // New Redirect - AFS GO (Business Solutions)
  { source: "/afsgo/afsgo-digital-solutions-and-tools", destination: "/solutions/business/pos-terminals", permanent: true },  
  { source: "/afsgo/afspay", destination: "/solutions/business/afspay-softpos", permanent: true },  
  { source: "/afsgo", destination: "/solutions/business", permanent: true },  

  // Value-Added Services
  { source: "/public/services/view/7/loyalty_solutions", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/8/data_analytics", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/9/3d_secure_", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/10/sms_services", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/services/view/11/24/7_contact_centre", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/13/interactive_epp_(easy_payment_plan)", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/14/chargeback_service", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/18/e-statements", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/services/view/20/value_added_services", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/technology/view/11/disaster_recovery_center", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/technology/view/11/disaster_recovery_center", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/technology/view/10/smart_alert_sms_messaging_system", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/technology/view/10/smart_alert_sms_messaging_system", destination: "/solutions/banks/value-added-services", permanent: true },

  // Fraud & Risk Management
  { source: "/public/services/view/12/online_fraud_management_services", destination: "/solutions/banks/fraud-risk-management", permanent: true },
  { source: "/public/technology/view/1/risknet", destination: "/solutions/banks/fraud-risk-management", permanent: true },
  { source: "/technology/view/1/risknet", destination: "/solutions/banks/fraud-risk-management", permanent: true },

 // Slightly Less Specific Redirects
  { source: "/services/view/21", destination: "/solutions/consumers/bpay", permanent: true },
  { source: "/services/view/22", destination: "/legal", permanent: true },
  { source: "/services/view/24", destination: "/legal", permanent: true },
  { source: "/services/view/2", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/3", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/4", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/services/view/5", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/services/view/15", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/services/view/16", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/technology/view/13", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/technology/view/13", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/technology/view/14", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/technology/view/14", destination: "/solutions/banks/card-issuing-processing", permanent: true },
  { source: "/public/services/view/7", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/8", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/9", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/10", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/services/view/11/24", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/services/view/11", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/13", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/14", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/18", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/services/view/20", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/technology/view/11", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/technology/view/11", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/technology/view/10", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/technology/view/10", destination: "/solutions/banks/value-added-services", permanent: true },
  { source: "/public/services/view/12", destination: "/solutions/banks/fraud-risk-management", permanent: true },
  { source: "/public/technology/view/1", destination: "/solutions/banks/fraud-risk-management", permanent: true },
  { source: "/technology/view/1", destination: "/solutions/banks/fraud-risk-management", permanent: true },
  { source: "/services/view/17", destination: "/solutions/business", permanent: true }, 

 //Level 5 

 //(All Default Redirects to News)
  { source: "/public/news/view/16/afs_gains_the_prestigious_iso_27001_accreditation", destination: "/news", permanent: true },
  { source: "/public/news/view/22/afs_conducts_payment_cards_growth_workshop", destination: "/news", permanent: true },
  { source: "/public/news/view/24/afs_becomes_the_first_processor_to_get_pci_dss_32_certification", destination: "/news", permanent: true },
  { source: "/public/news/view/24/afs_becomes_the_first_processor_to_get_pci_dss_3.2_certification", destination: "/news", permanent: true },
  { source: "/public/news/view/25/arab_financial_services_company_holds_the_annual_afs_conference", destination: "/news", permanent: true },
  { source: "/public/news/view/26/arab_financial_services_company_participates_in_cards__payments__east_africa", destination: "/news", permanent: true },
  { source: "/public/news/view/26/arab_financial_services_company_participates_in_cards_&_payments_–_east_africa", destination: "/news", permanent: true },
  { source: "/public/news/view/29/arab_financial_services_company_named_the_best_islamic_payment_solutions_provider__middle_east_", destination: "/news", permanent: true },
  { source: "/public/news/view/29/arab_financial_services_company_named_the_“best_islamic_payment_solutions_provider_–_middle_east”_", destination: "/news", permanent: true },
  { source: "/public/news/view/30/bahrain_industry_leaders_partner_to_launch_first_of_its_kind_mobile_payment_service", destination: "/news", permanent: true },
  { source: "/public/news/view/32/afs_partners_with_boloro_to_offer_the_first_near_field_communication_nfc_based_mobile_payments_in_bahrain", destination: "/news", permanent: true },
  { source: "/public/news/view/32/afs_partners_with_boloro_to_offer_the_first_near_field_communication_(nfc)_based_mobile_payments_in_bahrain", destination: "/news", permanent: true },
  { source: "/public/news/view/33/afs_hosts_regions_financial_leaders_to_discuss_response_to_fintech_disruption", destination: "/news", permanent: true },
  { source: "/public/news/view/33/afs_hosts_region’s_financial_leaders_to_discuss_response_to_fintech_disruption", destination: "/news", permanent: true },
  { source: "/public/news/view/34/afs_fintech_forum_highlights_need_for_innovative_banking_solutions", destination: "/news", permanent: true },
  { source: "/public/news/view/42/1st_middle_east__africa_fintech_forum_2017__video", destination: "/news", permanent: true },
  { source: "/public/news/view/43/afs_mobile_wallet_to_enable_cashless_payments_in_bahrain", destination: "/news", permanent: true },
  { source: "/public/news/view/44/batelco_and_afs_sign_partnership_agreement_for_mobile_wallet_solution_to_enable_cashless_payments_in_bahrain", destination: "/news", permanent: true },
  { source: "/public/news/view/45/al_salam_bankbahrain_and_afs_sign_partnership_agreement_to_launch_the_first_digital_payroll_program_solution_in_the_kingdom", destination: "/news", permanent: true },
  { source: "/public/news/view/45/al_salam_bank-bahrain_and_afs_sign_partnership_agreement_to_launch_the_first_digital_payroll_program_solution_in_the_kingdom", destination: "/news", permanent: true },
  { source: "/public/news/view/46/batelco_and_arab_financial_services_partner_to_launch_bwallet_a_new_fintech_service", destination: "/news", permanent: true },
  { source: "/public/news/view/46/batelco_and_arab_financial_services_partner_to_launch_bwallet:_a_new_fintech_service", destination: "/news", permanent: true },
  { source: "/public/news/view/48/bwallet_launch_2018", destination: "/news", permanent: true },
  { source: "/public/news/view/49/under_the_patronage_of_the_central_bank_of_bahrain_middle_east__africa_fintech_forum_2_to_be_held_in_march_in_manama", destination: "/news", permanent: true },
  { source: "/public/news/view/50/innovative_solution_to_provide_convenience_for_employers_and_employees", destination: "/news", permanent: true },
  { source: "/public/news/view/52/arab_financial_services_afs_becomes_iso_270012013_certificated_information_security_management_system_", destination: "/news", permanent: true },
  { source: "/public/news/view/52/arab_financial_services_(afs)_becomes_iso_27001:2013_certificated_(information_security_management_system)_", destination: "/news", permanent: true },
  { source: "/public/news/view/53/bwallet_and_mukta_a2_cinemas_exclusive_offer_on_movie_tickets", destination: "/news", permanent: true },
  { source: "/public/news/view/56/afs_chairman_at_the_2nd_middle_east__africa_fintech_forum_financial_disruption_is_a_catalyst_for__change_and_an_opportunity", destination: "/news", permanent: true },
  { source: "/public/news/view/57/the_2nd_middle_east__africa_fintech_forum", destination: "/news", permanent: true },
  { source: "/public/news/view/58/bwallet_and_dana_cinema_exclusive_offer_on_movie_tickets", destination: "/news", permanent: true },
  { source: "/public/news/view/59/the_2nd_middle_east__africa_fintech_forum_2018__press_coverage", destination: "/news", permanent: true },
  { source: "/public/news/view/60/bwallet_leading_with_another_exclusive_offer_on_movie_tickets_at_cineco", destination: "/news", permanent: true },
  { source: "/public/news/view/61/afs_increases_focus_on_frictionless_payment_solutions_in_the_region", destination: "/news", permanent: true },
  { source: "/public/news/view/62/lulu_partners_with_bwallet_", destination: "/news", permanent: true },
  { source: "/public/news/view/63/bwallet_partners_with_elite_hospitality_group,_bahrain", destination: "/news", permanent: true },
  { source: "/public/news/view/64/bwallet_ties_up_with_solidarity_bahrain", destination: "/news", permanent: true },
  { source: "/public/news/view/65/the_bibf_students_go_cashless_with_bwallet_", destination: "/news", permanent: true },
  { source: "/public/news/view/66/bank_abc_and_afs_to_hold_the_3rd_fintech_forum_next_february_", destination: "/news", permanent: true },
  { source: "/public/news/view/67/bwallet_ties_up_with_bmmi_group", destination: "/news", permanent: true },
  { source: "/public/news/view/68/batelco_and_afs_collect_smart_finance_solution_award_at_bahrain_sustainable__smart_cities_forum_2018", destination: "/news", permanent: true },
  { source: "/public/news/view/75/the_bibf_and_afs_sign_mou_to_launch_“payments_academy”", destination: "/news", permanent: true },
  { source: "/public/news/view/77/“king_of_disruptors”_to_speak_at_the_3rd_middle_east_and_africa_fintech_forum_in_manama", destination: "/news", permanent: true },
  { source: "/public/news/view/78/afs_and_ahli_united_bank_partner_to_offer_innovative_acquiring_solutions_in_bahrain", destination: "/news", permanent: true },
  { source: "/public/news/view/79/bwallet_more_than_doubles_balance_and_transaction_limits", destination: "/news", permanent: true },
  { source: "/public/news/view/80/gdn_subscriptions_now_easily_available_through_bwallet", destination: "/news", permanent: true },
  { source: "/public/news/view/81/arab_financial_services_gets_certified_on_pci_dss_v3.2.1_by_sisa", destination: "/news", permanent: true },
  { source: "/public/news/view/82/anthony_thomson_to_speak_again_at_the_3rd_middle_east_and_africa_fintech_forum_in_manama", destination: "/news", permanent: true },
  { source: "/public/news/view/83/al_hilal_hospital_launches_bwallet_payments_", destination: "/news", permanent: true },
  { source: "/public/news/view/85/afs_launches_state-of-the-art_android-based_pos_terminals_in_bahrain_", destination: "/news", permanent: true },
  { source: "/public/news/view/87/al_salam_bank-bahrain_and_afs_offering_“al_rateb”_–_the_first_cashless_payment_service_in_the_kingdom_for_blue_collar_workers",   
destination: "/news", permanent: true },
  { source: "/public/news/view/88/bwallet_brings_cashless_dining_to_al_abraaj_group", destination: "/news", permanent: true },
  { source: "/public/news/view/89/al_salam_bank-bahrain_and_afs_officially_launch_“al_rateb”_payment_protection_scheme", destination: "/news", permanent: true },
  { source: "/public/news/view/90/afs_adds_international_prepaid_mobile_top_up_to_suite_of_services", destination: "/news", permanent: true },
  { source: "/public/news/view/91/afs_is_bahrain’s_first_acquirer_to_obtain_benefit_switch_certification_for_pos_contactless_transactions", destination: "/news", permanent: true },
  { source: "/public/news/view/92/afs_and_gulf_african_bank_partnership_delivers_east_africa’s_first_sharia’h_compliant_credit_card", destination: "/news", permanent: true },
  { source: "/public/news/view/94/cinépolis_moviegoers_enjoy_cashless_viewing_with_bwallet", destination: "/news", permanent: true },
  { source: "/public/news/view/95/bwallet’s_international_money_transfer_service_expands_to_uk", destination: "/news", permanent: true },
  { source: "/public/news/view/96/devji_rolls_out_instore_bwallet_payments", destination: "/news", permanent: true },
  { source: "/public/news/view/97/bwallet_and_university_of_bahrain_collaborate_on_fintech_initiative", destination: "/news", permanent: true },
  { source: "/public/news/view/98/afs_recognized_as_best_fintech_solutions_company_2019", destination: "/news", permanent: true },
  { source: "/public/news/view/100/al_jazeera_shipping_company_adopts_al_rateb,_the_kingdom’s_first_digital_payroll_solution_", destination: "/news", permanent: true },
  { source: "/public/news/view/101/university_of_bahrain_students_win_prizes_in_afs’_bwallet_challenge", destination: "/news", permanent: true },
  { source: "/public/news/view/102/bwallet_celebrates_second_anniversary_in_bahrain", destination: "/news", permanent: true },

  //All specific redirects to specific news
  { source: "/public/news/view/150/arab_financial_services_successfully_concludes_2023_summer_internship_program_afs_isuites", destination: "/news/arab-financial-services-successfully-concludes-2023-summer-internship-program-afs-isuites", permanent: true },
  { source: "/public/news/view/151/launch_of_bpay_youth_cards:_empowering_financial_independence_in_younger_generation", destination: "/news/launch-of-bpay-youth-cards-empowering-financial-independence-in-younger-generation", permanent: true },
  { source: "/public/news/view/151/launch_of_bpay_youth_cards_empowering_financial_independence_in_younger_generation", destination: "/news/launch-of-bpay-youth-cards-empowering-financial-independence-in-younger-generation", permanent: true },
  { source: "/public/news/view/152/launch_of_bpay_youth_cards:_empowering_financial_independence_in_younger_generation", destination: "/news/launch-of-bpay-youth-cards-empowering-financial-independence-in-younger-generation", permanent: true },
  { source: "/public/news/view/152/launch_of_bpay_youth_cards_empowering_financial_independence_in_younger_generation", destination: "/news/launch-of-bpay-youth-cards-empowering-financial-independence-in-younger-generation", permanent: true },
  { source: "/public/news/view/153/afs_launches_single_technology_platform_to_integrate_all_dining_solutions_for_fb_merchants", destination: "/news/afs-launches-single-technology-platform-to-integrate-all-dining-solutions-for-f-and-b-merchants", permanent: true },
  { source: "/public/news/view/154/belgian-bahraini_fintech_partnership_explored", destination: "/belgian-bahraini-fintech-partnership-explored", permanent: true },
  { source: "/public/news/view/155/afs_and_kiyaai_announce_dynamic_partnership_to_revolutionise_digital_banking_solutions_in_the_region", destination: "/afs-and-kiya-ai-announce-dynamic-partnership-to-revolutionise-digital-banking-solutions-in-the-region", permanent: true },
  { source: "/public/news/view/156/afs_conducts_media_workshop_to_showcase_latest_cloudbased_restaurant_first_solution", destination: "/afs-conducts-media-workshop-to-showcase-latest-cloud-based-restaurant-first-solution", permanent: true },
  { source: "/public/news/view/156/afs_conducts_media_workshop_to_showcase_latest_cloud-based_restaurant_-first_solution", destination: "/afs-conducts-media-workshop-to-showcase-latest-cloud-based-restaurant-first-solution", permanent: true },
  { source: "/public/news/view/157/arab_financial_services_afs_enter_strategic_alliance_with_xpence_to_innovate_sme_financial_management_in_bahrain", destination: "/arab-financial-services-enter-strategic-alliance-with-xpence-to-innovate-sme-financial-management-in-bahrain", permanent: true },
  { source: "/public/news/view/157/arab_financial_services_(afs)_enter_strategic_alliance_with_xpence_to_innovate_sme_financial_management_in_bahrain", destination: "/arab-financial-services-enter-strategic-alliance-with-xpence-to-innovate-sme-financial-management-in-bahrain", permanent: true },
  { source: "/public/news/view/158/afs_transaction_index_seasonopening_bahrain_gp_delivers_66_surge_in_spends", destination: "/afs-transaction-index-season-opening-bahrain-gp-delivers-66-percent-surge-in-spends", permanent: true },
  { source: "/public/news/view/159/aci_worldwide_and_arab_financial_services_to_drive_payments_modernization_for_banks_and_merchants_in_the_middle_east", destination: "/news/aci-worldwide-and-arab-financial-services-to-drive-payments-modernization-for-banks-and-merchants-in-the-middle-east", permanent: true },

  //Level 4
 
 //(All Default Redirects to News)
 { source: "/public/news/view/16", destination: "/news", permanent: true },
 { source: "/public/news/view/22", destination: "/news", permanent: true },
 { source: "/public/news/view/24", destination: "/news", permanent: true },
 { source: "/public/news/view/25", destination: "/news", permanent: true },
 { source: "/public/news/view/26", destination: "/news", permanent: true },
 { source: "/public/news/view/29", destination: "/news", permanent: true },
 { source: "/public/news/view/30", destination: "/news", permanent: true },
 { source: "/public/news/view/32", destination: "/news", permanent: true },
 { source: "/public/news/view/33", destination: "/news", permanent: true },
 { source: "/public/news/view/34", destination: "/news", permanent: true },
 { source: "/public/news/view/42", destination: "/news", permanent: true },
 { source: "/public/news/view/43", destination: "/news", permanent: true },
 { source: "/public/news/view/44", destination: "/news", permanent: true },
 { source: "/public/news/view/45", destination: "/news", permanent: true },
 { source: "/public/news/view/46", destination: "/news", permanent: true },
 { source: "/public/news/view/48", destination: "/news", permanent: true },
 { source: "/public/news/view/49", destination: "/news", permanent: true },
 { source: "/public/news/view/50", destination: "/news", permanent: true },
 { source: "/public/news/view/52", destination: "/news", permanent: true },
 { source: "/public/news/view/53", destination: "/news", permanent: true },
 { source: "/public/news/view/56", destination: "/news", permanent: true },
 { source: "/public/news/view/57", destination: "/news", permanent: true },
 { source: "/public/news/view/58", destination: "/news", permanent: true },
 { source: "/public/news/view/59", destination: "/news", permanent: true },
 { source: "/public/news/view/60", destination: "/news", permanent: true },
 { source: "/public/news/view/61", destination: "/news", permanent: true },
 { source: "/public/news/view/62", destination: "/news", permanent: true },
 { source: "/public/news/view/63", destination: "/news", permanent: true },
 { source: "/public/news/view/64", destination: "/news", permanent: true },
 { source: "/public/news/view/65", destination: "/news", permanent: true },
 { source: "/public/news/view/66", destination: "/news", permanent: true },
 { source: "/public/news/view/67", destination: "/news", permanent: true },
 { source: "/public/news/view/68", destination: "/news", permanent: true },
 { source: "/public/news/view/75", destination: "/news", permanent: true },
 { source: "/public/news/view/77", destination: "/news", permanent: true },
 { source: "/public/news/view/78", destination: "/news", permanent: true },
 { source: "/public/news/view/79", destination: "/news", permanent: true },
 { source: "/public/news/view/80", destination: "/news", permanent: true },
 { source: "/public/news/view/81", destination: "/news", permanent: true },
 { source: "/public/news/view/82", destination: "/news", permanent: true },
 { source: "/public/news/view/83", destination: "/news", permanent: true },
 { source: "/public/news/view/85", destination: "/news", permanent: true },
 { source: "/public/news/view/87", destination: "/news", permanent: true },
 { source: "/public/news/view/88", destination: "/news", permanent: true },
 { source: "/public/news/view/89", destination: "/news", permanent: true },
 { source: "/public/news/view/90", destination: "/news", permanent: true },
 { source: "/public/news/view/91", destination: "/news", permanent: true },
 { source: "/public/news/view/92", destination: "/news", permanent: true },
 { source: "/public/news/view/93", destination: "/news", permanent: true },
 { source: "/public/news/view/94", destination: "/news", permanent: true },
 { source: "/public/news/view/95", destination: "/news", permanent: true },
 { source: "/public/news/view/96", destination: "/news", permanent: true },
 { source: "/public/news/view/97", destination: "/news", permanent: true },
 { source: "/public/news/view/98", destination: "/news", permanent: true },
 { source: "/public/news/view/99", destination: "/news", permanent: true },
 { source: "/public/news/view/100", destination: "/news", permanent: true },
 { source: "/public/news/view/101", destination: "/news", permanent: true },
 { source: "/public/news/view/102", destination: "/news", permanent: true },

 //All specific redirects to specific news
 { source: "/public/news/view/150", destination: "/news/arab-financial-services-successfully-concludes-2023-summer-internship-program-afs-isuites", permanent: true },
 { source: "/public/news/view/151", destination: "/news/launch-of-bpay-youth-cards-empowering-financial-independence-in-younger-generation", permanent: true },
 { source: "/public/news/view/152", destination: "/news/launch-of-bpay-youth-cards-empowering-financial-independence-in-younger-generation", permanent: true },
 { source: "/public/news/view/153", destination: "/news/afs-launches-single-technology-platform-to-integrate-all-dining-solutions-for-f-and-b-merchants", permanent: true },
 { source: "/public/news/view/154", destination: "/news/belgian-bahraini-fintech-partnership-explored", permanent: true },
 { source: "/public/news/view/155", destination: "/news/afs-and-kiya-ai-announce-dynamic-partnership-to-revolutionise-digital-banking-solutions-in-the-region", permanent: true },
 { source: "/public/news/view/156", destination: "/news/afs-conducts-media-workshop-to-showcase-latest-cloud-based-restaurant-first-solution", permanent: true },
 { source: "/public/news/view/157", destination: "/news/arab-financial-services-enter-strategic-alliance-with-xpence-to-innovate-sme-financial-management-in-bahrain", permanent: true },
 { source: "/public/news/view/158", destination: "/news/afs-transaction-index-season-opening-bahrain-gp-delivers-66-percent-surge-in-spends", permanent: true },
 { source: "/public/news/view/159", destination: "/news//aci-worldwide-and-arab-financial-services-to-drive-payments-modernization-for-banks-and-merchants-in-the-middle-east", permanent: true },

 //Level 3
  { source: "/public/news/view", destination: "/news", permanent: true },
  { source: "/news/view/159", destination: "/news/aci-worldwide-and-arab-financial-services-to-drive-payments-modernization-for-banks-and-merchants-in-the-middle-east", permanent: true },
 
 //Level 2
  { source: "/news/view/", destination: "/news", permanent: true }, 
  { source: "/services/view", destination: "/solutions", permanent: true },
  { source: "/public/services", destination: "/solutions", permanent: true },
 
 
 // Broader AFS Redirects
  { source: "/public/news", destination: "/news", permanent: true },
  { source: "/public/technology/view", destination: "/solutions", permanent: true },
  { source: "/technology/view/", destination: "/solutions", permanent: true }, // More specific than /technology
  { source: "/services", destination: "/solutions", permanent: true },
  { source: "/public/technology", destination: "/solutions", permanent: true },
  { source: "/technology", destination: "/solutions", permanent: true },
  { source: "/bpayoffers", destination: "/solutions/consumers/bpay", permanent: true },
  { source: "/privacy_notice", destination: "/legal", permanent: true },
  { source: "/bpay_fees_and_charges", destination: "/legal", permanent: true },
]

module.exports = redirects;